-- =====================================================
-- Sunflower Dental Lab  --  seed data
-- Idempotent: safe to re-run; uses INSERT IGNORE.
-- =====================================================

-- Categories (display order matches original sample)
INSERT IGNORE INTO categories (code, label, sort_order) VALUES
  ('Ceramic', 'Ceramic', 10),
  ('Implant', 'Implant', 20),
  ('Metal', 'Full Metal', 30),
  ('Attachment', 'Attachment', 40),
  ('Acrylic', 'Acrylic', 50),
  ('Treatment', 'Treatment', 60);

-- Products
INSERT IGNORE INTO products (code, name, category_id, price, note) VALUES
  ('CER-001', 'Full Zirconia / Inlay / Onlay', (SELECT id FROM categories WHERE code='Ceramic'), 300.00, 'due to aesthetic'),
  ('CER-002', 'Layered Zirconia', (SELECT id FROM categories WHERE code='Ceramic'), 310.00, ''),
  ('CER-003', 'Zirconia Veneer', (SELECT id FROM categories WHERE code='Ceramic'), 310.00, ''),
  ('CER-004', 'Multilayer Zirconia / Inlay / Onlay', (SELECT id FROM categories WHERE code='Ceramic'), 300.00, ''),
  ('CER-005', 'IPS e.max Crown', (SELECT id FROM categories WHERE code='Ceramic'), 315.00, ''),
  ('CER-006', 'IPS e.max Prep Veneer', (SELECT id FROM categories WHERE code='Ceramic'), 315.00, ''),
  ('CER-007', 'IPS e.max Inlay / Onlay', (SELECT id FROM categories WHERE code='Ceramic'), 310.00, ''),
  ('CER-008', 'PFM Crown - Argent Alloy (Co-Cr)', (SELECT id FROM categories WHERE code='Ceramic'), 150.00, ''),
  ('CER-009', 'PFM Crown - Semi/High Precious', (SELECT id FROM categories WHERE code='Ceramic'), 150.00, '+gold cost'),
  ('CER-010', 'Metal Margin', (SELECT id FROM categories WHERE code='Ceramic'), 50.00, ''),
  ('CER-011', 'Maryland Bridge (1 pontic / 2 wings)', (SELECT id FROM categories WHERE code='Ceramic'), 500.00, ''),
  ('CER-012', 'Rest for PFM', (SELECT id FROM categories WHERE code='Ceramic'), 50.00, ''),
  ('CER-013', 'Porcelain Margin / Porcelain Shoulder', (SELECT id FROM categories WHERE code='Ceramic'), 40.00, ''),
  ('CER-014', 'Gum Porcelain for PFM', (SELECT id FROM categories WHERE code='Ceramic'), 50.00, ''),
  ('CER-015', 'Gum Porcelain for Zirconia', (SELECT id FROM categories WHERE code='Ceramic'), 50.00, ''),
  ('CER-017', '3D Printed Quadrant Model (Upper/Lower)', (SELECT id FROM categories WHERE code='Ceramic'), 35.00, '(FOC)'),
  ('CER-018', '3D Printed Full Arch Model (Upper/Lower)', (SELECT id FROM categories WHERE code='Ceramic'), 40.00, '(FOC)'),
  ('IMP-019', 'Implant PFM Crown - Argent Cr & Co', (SELECT id FROM categories WHERE code='Implant'), 230.00, ''),
  ('IMP-020', 'Implant PFM Crown - Semi/High Precious', (SELECT id FROM categories WHERE code='Implant'), 240.00, '+gold cost'),
  ('IMP-021', 'Implant E-max Crown', (SELECT id FROM categories WHERE code='Implant'), 450.00, ''),
  ('IMP-022', 'Implant Full/Layered Zirconia Crown', (SELECT id FROM categories WHERE code='Implant'), 400.00, ''),
  ('IMP-023', 'Implant Tissue Model', (SELECT id FROM categories WHERE code='Implant'), 0.00, ''),
  ('IMP-024', 'Cast / Milling Abutment', (SELECT id FROM categories WHERE code='Implant'), 105.00, ''),
  ('IMP-025', 'Implant All-on-4 Malong Framework', (SELECT id FROM categories WHERE code='Implant'), 4100.00, ''),
  ('IMP-026', 'Implant All-on-4 Titanium Bar', (SELECT id FROM categories WHERE code='Implant'), 4000.00, ''),
  ('IMP-027', 'Implant All-on-5 Malong Framework', (SELECT id FROM categories WHERE code='Implant'), 4125.00, ''),
  ('IMP-028', 'Implant All-on-5/6 Titanium Bar', (SELECT id FROM categories WHERE code='Implant'), 4075.00, ''),
  ('IMP-029', 'Implant All-on-6 Malong Framework', (SELECT id FROM categories WHERE code='Implant'), 4150.00, ''),
  ('IMP-030', 'Surgical Guide', (SELECT id FROM categories WHERE code='Implant'), 550.00, ''),
  ('IMP-031', 'All-on-4 Implant PFM Bridge', (SELECT id FROM categories WHERE code='Implant'), 300.00, ''),
  ('IMP-033', 'Implant Zirconia Crown + Customized Abutment', (SELECT id FROM categories WHERE code='Implant'), 650.00, ''),
  ('IMP-034', 'Custom Titanium Abutment', (SELECT id FROM categories WHERE code='Implant'), 320.00, ''),
  ('IMP-035', 'Custom Zirconia Abutment', (SELECT id FROM categories WHERE code='Implant'), 500.00, ''),
  ('IMP-036', 'Custom Angle Abutment', (SELECT id FROM categories WHERE code='Implant'), 525.00, ''),
  ('IMP-037', 'Custom Multi-Abutment', (SELECT id FROM categories WHERE code='Implant'), 590.00, ''),
  ('IMP-038', 'Analog', (SELECT id FROM categories WHERE code='Implant'), 75.00, '(FOC)'),
  ('IMP-039', 'Full Implant Hybrid Denture Wax-up', (SELECT id FROM categories WHERE code='Implant'), 325.00, ''),
  ('IMP-391', 'Full Implant Hybrid Denture Process', (SELECT id FROM categories WHERE code='Implant'), 200.00, ''),
  ('MET-040', 'Full Metal Crown / Inlay / Onlay (Co-Cr)', (SELECT id FROM categories WHERE code='Metal'), 100.00, ''),
  ('MET-041', 'Full Metal Post (Co-Cr)', (SELECT id FROM categories WHERE code='Metal'), 50.00, ''),
  ('MET-042', 'Full Gold Crown', (SELECT id FROM categories WHERE code='Metal'), 90.00, '+gold cost'),
  ('ATT-043', 'Telescope Crown - Primary', (SELECT id FROM categories WHERE code='Attachment'), 140.00, ''),
  ('ATT-044', 'Telescope Crown - Secondary', (SELECT id FROM categories WHERE code='Attachment'), 180.00, ''),
  ('ATT-045', 'Composite on Telescope', (SELECT id FROM categories WHERE code='Attachment'), 150.00, ''),
  ('ATT-046', 'Precl-mortixn Attachment (Bredent Vario Soft Ball)', (SELECT id FROM categories WHERE code='Attachment'), 390.00, ''),
  ('ATT-047', 'Precl-vertixp Attachment (Slot)', (SELECT id FROM categories WHERE code='Attachment'), 400.00, ''),
  ('ATT-048', 'MKI Attachment (incl. parts)', (SELECT id FROM categories WHERE code='Attachment'), 400.00, ''),
  ('ATT-049', 'Precl Attachment (incl. parts)', (SELECT id FROM categories WHERE code='Attachment'), 260.00, ''),
  ('ATT-050', 'Precl-clixp-p Attachment (Ball/Cap)', (SELECT id FROM categories WHERE code='Attachment'), 350.00, ''),
  ('ATT-051', 'Ceka-ol 0275 Attachment (adjustable)', (SELECT id FROM categories WHERE code='Attachment'), 400.00, ''),
  ('ATT-052', 'Keyslide-set Attachment', (SELECT id FROM categories WHERE code='Attachment'), 375.00, ''),
  ('ATT-053', 'Normal Precious Attachment', (SELECT id FROM categories WHERE code='Attachment'), 270.00, ''),
  ('ATT-054', 'Full Metal Framework (Co-Cr)', (SELECT id FROM categories WHERE code='Attachment'), 200.00, ''),
  ('ATT-055', 'Small Metal Framework / Unilateral (Co-Cr)', (SELECT id FROM categories WHERE code='Attachment'), 150.00, ''),
  ('ATT-056', 'Clear-met Framework', (SELECT id FROM categories WHERE code='Attachment'), 300.00, ''),
  ('ATT-057', 'Vitallium Framework', (SELECT id FROM categories WHERE code='Attachment'), 340.00, ''),
  ('ATT-058', 'Full Pure Titanium Framework', (SELECT id FROM categories WHERE code='Attachment'), 360.00, ''),
  ('ATT-059', 'Side Pure Titanium Framework', (SELECT id FROM categories WHERE code='Attachment'), 340.00, ''),
  ('ACR-060', 'Wax-up Denture per Tooth', (SELECT id FROM categories WHERE code='Acrylic'), 20.00, '>6 teeth: RM15/each'),
  ('ACR-061', 'Process BIOHPP / Peek Denture', (SELECT id FROM categories WHERE code='Acrylic'), 500.00, ''),
  ('ACR-065', 'Process Acrylic Denture', (SELECT id FROM categories WHERE code='Acrylic'), 150.00, ''),
  ('ACR-066', 'Process COCR Denture', (SELECT id FROM categories WHERE code='Acrylic'), 225.00, ''),
  ('ACR-067', 'Process Titanium/Attachment/Telescope Denture', (SELECT id FROM categories WHERE code='Acrylic'), 350.00, ''),
  ('ACR-068', 'Process with 199 Acrylic', (SELECT id FROM categories WHERE code='Acrylic'), 180.00, ''),
  ('ACR-069', 'Process Valplast Denture', (SELECT id FROM categories WHERE code='Acrylic'), 200.00, ''),
  ('ACR-070', 'Wire Clasp', (SELECT id FROM categories WHERE code='Acrylic'), 10.00, ''),
  ('ACR-071', 'Valplast / Clear / Shade Clasp', (SELECT id FROM categories WHERE code='Acrylic'), 100.00, ''),
  ('ACR-072', 'Reline', (SELECT id FROM categories WHERE code='Acrylic'), 135.00, ''),
  ('ACR-073', 'Add Mesh on Acrylic Denture', (SELECT id FROM categories WHERE code='Acrylic'), 75.00, ''),
  ('ACR-074', 'Wax Rim on Hard Base', (SELECT id FROM categories WHERE code='Acrylic'), 55.00, ''),
  ('ACR-075', 'Bite Block / Wax Rim', (SELECT id FROM categories WHERE code='Acrylic'), 40.00, ''),
  ('ACR-076', 'Special Tray (S/T)', (SELECT id FROM categories WHERE code='Acrylic'), 50.00, ''),
  ('ACR-077', 'Soft Reline', (SELECT id FROM categories WHERE code='Acrylic'), 140.00, ''),
  ('ACR-078', 'Clear Acrylic Fundus', (SELECT id FROM categories WHERE code='Acrylic'), 200.00, ''),
  ('ACR-079', 'Temporary CAD/CAM Crown', (SELECT id FROM categories WHERE code='Acrylic'), 50.00, ''),
  ('TRT-080', 'Soft / Hard Mouth Guard', (SELECT id FROM categories WHERE code='Treatment'), 140.00, ''),
  ('TRT-081', 'Clear Retainer', (SELECT id FROM categories WHERE code='Treatment'), 140.00, ''),
  ('TRT-082', 'Mouth Guard (Soft Inside / Hard Outside)', (SELECT id FROM categories WHERE code='Treatment'), 180.00, ''),
  ('TRT-083', 'Acrylic Mouth Guard', (SELECT id FROM categories WHERE code='Treatment'), 175.00, ''),
  ('TRT-084', 'Removable Framework Expander', (SELECT id FROM categories WHERE code='Treatment'), 400.00, ''),
  ('TRT-085', 'Fixed Expander', (SELECT id FROM categories WHERE code='Treatment'), 400.00, ''),
  ('TRT-086', 'Screw Expander', (SELECT id FROM categories WHERE code='Treatment'), 425.00, '+parts fee'),
  ('TRT-087', 'Twin Block', (SELECT id FROM categories WHERE code='Treatment'), 325.00, '+component'),
  ('TRT-088', 'TPA', (SELECT id FROM categories WHERE code='Treatment'), 200.00, ''),
  ('TRT-089', 'Hawley Retainer', (SELECT id FROM categories WHERE code='Treatment'), 200.00, ''),
  ('TRT-090', 'Space Retainer', (SELECT id FROM categories WHERE code='Treatment'), 180.00, '');

-- Default settings
INSERT IGNORE INTO settings (k, v) VALUES
  ('invoice_prefix', 'SF'),
  ('invoice_next',   '576');
